apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gabs-full/chatbot-infra
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-bot-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gabs-full/chatbot-infra
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-webhook-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gabs-full/chatbot-infra
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-lambda-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gabs-full/chatbot-infra
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-zapi-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gabs-full/chatbot-infra
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
