apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZW8zQ1pvWVhGOWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qVXdNekl3TURaYUZ3MHpOakF5TWpNd016STFNRFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURSYml1aVR0cGVHNHJQMXNMQWlwWjJGTmNuL1RXT2E5UFRNQUp4dzYrOFNpK1RmR0NTVFNud3BKd00KK3E0VXd1eXc1NmZvKzQ0NU5LL2NKb2dzK1prdDNteEFZODVOaUhoSmlmWWExVmtibVZJMEs2Qm1nM29BOURLTAo0UEF3SG8wQnZtWS9tZmJGSE5CL3FsSnJLOW1SdlJsSjBMKzhjT1BoTmZFbHh6MzhLNzhYeTR0dmNBNFVpcjBvCm1vZHVBcFdqWmgxeS9sNGFVcUFLa01YdEJWOUMyb01yMVlVd3YzNVJUNTV4NVU5YW5zMmUzWGlzamgra0hLZzUKQVdYTm5Odk11K2ZIQk51a1BDYjlONGJQY21CZm9mVys1WUNweHlFdk5CS3ZacFZMc2FQZlczVHBHTHAwZHFFYgpJODlnZ2cwT1Y1UGVhSEJHTkQ2bWRlS2NHTldCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRR2NybFdDQ1d6b2RhMXBtMnVsRlRUNnZUdU1qQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVpPNWFhcmY3QgpySU0wMHRoVE0rUGJQbnpKWDJVQVJ3WGpmTkFVdVZra3I0Mkx0Z01lZGk4UXhLRS8xZ0tENExMU1NUQ2thbFJWCk5iVUhyaldMSUoxNkthTDlwS0RYSTc4elBiYzVlejkyeVJQYlVqR3lEd0pPTzkrMzIxMDN1V0FCUTdTby82V24KbVRGQ1hXaHZlZkEvaXBFVnIxeCtFNHBIWXNzTFVqUjV0SXdYZDU4QW9QVm9IdllGQWRqa3VRYXJSdlFqMnNoQgp3QkZvQzExdldlbmR2NHdRYWFBUmcwRG12dkpuemNOS2RNQVFRZ1RQVGpMVVRSSUJxaHVHUnQ2N0Z0VkpQeWswCnZ2ZE5mQmdQSGxWZHlYOEFldEhyYjVJR29oRFdQUlg0SGdLNnNRNkNpaFBydDk4OGdYamhFRE13TXBqWi9henIKTnBJakhiQSs3bWkvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://503F2BC664FCC4D2F5388317B22A929E.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
    user: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
  name: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
current-context: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:572221303564:cluster/chatbot-eks-eksCluster-a2f2daa
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - chatbot-eks-eksCluster-a2f2daa
      - --output
      - json
      command: aws
